# /etc/nginx/sites-available/demo-academia.klaveai.es
# Enlazar: ln -s /etc/nginx/sites-available/demo-academia.klaveai.es /etc/nginx/sites-enabled/

server {
    listen 80;
    server_name demo-academia.klaveai.es;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name demo-academia.klaveai.es;

    ssl_certificate     /etc/letsencrypt/live/demo-academia.klaveai.es/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/demo-academia.klaveai.es/privkey.pem;
    include             /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam         /etc/letsencrypt/ssl-dhparams.pem;

    location / {
        proxy_pass         http://127.0.0.1:3005;
        proxy_http_version 1.1;
        proxy_set_header   Upgrade $http_upgrade;
        proxy_set_header   Connection 'upgrade';
        proxy_set_header   Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}

# Comandos de despliegue:
# certbot --nginx -d demo-academia.klaveai.es
# nginx -t && systemctl reload nginx
